const os = require('os')
console.log(os.platform())
console.log(os.type())
console.log(os.arch())
console.log(os.release())
console.log(os.hostname())
console.log(os.uptime())
console.log((os.uptime()/3600).toFixed(2))
console.log(os.totalmem())
console.log((os.totalmem()/1024**3).toFixed(2))
console.log(os.freemem())
console.log((os.freemem()/1024**3).toFixed(2))
console.log(os.cpus())
console.log(os.networkInterfaces())
console.log(os.homedir())
console.log(os.tmpdir())
console.log(os.userInfo())